name: Deploy Shiny App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RENV_CONFIG_SANDBOX_ENABLED: FALSE

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            pak
          needs: renv

      - name: Restore R packages using renv.lock
        run: |
          install.packages("pak")
          pak::pkglock_install("renv.lock")
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo(name='hgesdrn', token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appDir = ".", appName = "TBE_QC_shiny", forceUpdate = TRUE)
        shell: Rscript {0}
